version: '3.8'

services:
  # 1. Nuestro contenedor de Base de Datos
  mysqldb:
    image: mysql:8.0
    container_name: sprint3-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=usuarios # <-- Pon aquí el nombre exacto de tu BBDD
      - MYSQL_ROOT_PASSWORD=12345
    command: --default-authentication-plugin=mysql_native_password

  # 2. Nuestro contenedor de la Aplicación Java
  backend:
    build: . # Le dice a Docker que busque tu Dockerfile en esta misma carpeta
    container_name: sprint3-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb # Espera a que la BD exista antes de arrancar Java
    environment:
      # Estos parámetros sobreescriben tu application.properties para que se conecte a Docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/usuarios?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

  sonarqube:
    image: sonarqube:26.1.0.118079-community
    container_name: sprint3-sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_FORCEAUTHENTICATION=false