version: '3.8'

services:

  incidencias-service:
    build: ./incidencias-service
    container_name: sprint3-incidencias
    ports:
      - "8082:8082"
    networks:
      - red-generador

  # 3. Microservicio de Usuarios (Arranca después y se conecta a Incidencias y BD)
  usuarios-service:
    build: ./usuarios-service
    container_name: sprint3-usuarios
    ports:
      - "8081:8081"
    depends_on:
      - incidencias-service
    networks:
      - red-generador

networks:
  red-generador:
      driver: bridge